### PR TITLE
feature(sponsors): Add direct sponsors

### PR DESCRIPTION
**Pull request by 3bobchen**
Screenshot 2024-02-12 at 11 55 36 am

### CODE REVIEW

**Comment by 3bobchen** [comment]
Oh wait i need a margin on shorter screens - oops

**Review by francojreyes — COMMENTED** [review]
Looks good but doesn't seem to work on mobile. Also looks kind of weird when I run it locally, like the logo is touching the bottom of my screen. Can you add some padding below?

Also why have you got rid of the spaces in every object lmao. Can you configure ur WebStorm to not do that.

**Comment by 3bobchen** [comment]
@francojreyes comment points addressed. 

Regarding brace spaces, i think ive added them back but if theyre still weird or too spacy, might be easier for you to run code tidy on your end? lmk

**Comment by francojreyes** [comment]
Lol, bracket spacing is wack now. It's supposed to be, if you ever have an object literal like `{x: 1, y: 2}` then it should be spaced to be `{ x: 1, y: 2 }`. This doesn't apply to normal brackets or square brackets. Also doesn't apply to other uses of curly brackets like in JSX props e.g. `mb={3}` is all good. I'll run my formatter when it's ready to merge.

I think the margin at the bottom is way too big now lol. Maybe it looks okay when everything fits on the screen, but otherwise it's like you can just scroll down past the logos into blank space. I think there should be very little margin, just enough so that it doesn't look like the logos are touching the bottom of the screen.

Lastly, thoughts on having the images link to the company website?

**Comment by 3bobchen** [comment]
thanks @francojreyes 

Added URL links, and reduced margin size. I also reordered the logo so TikTok is in the center since they were the first full sponsor. Feel free to discuss if you preferred jane st in the center. 

Otherwise, I'll leave to you to merge / code tidy. I reverted my bracket space settings - its honestly a mess with webstorm.

**Review by francojreyes — APPROVED** [review]

**Pull request merged**
